### ISSUE TITLE
Ben Tre dataset cannot load after restructuring

### ISSUE THREAD

**Issue by hqnghi88** [WARMTeam/CoVid19#12]
Chosing 1 (Ben tre dataset ) cause exception 
2 occurrences in 2 agents at cycle 0: Error: nil value detected
in schools[l] <- buildings_per_activity[type] as_map (each :: each.shape.area);
in schools[l] <- buildings_per_activity[type] as_map (each :: each.shape.area);
in loop l over: possible_schools.keys  {
	max_student_age <- max([max_student_age,max(l)]);
	min_student_age <- min([min_student_age,min(l)]);
	string type <- possible_schools[l];
	schools[l] <- buildings_per_activity[type] as_map (each :: each.shape.area);
}
...in agents Simulation 0, Comparison0
Probably come from the fact that this dataset doesn't have "university" building type.

**Comment by AlexisDrogoul** [comment]
Yep. Probably we need to check first if the value is not nil (i.e. that there are buildings of this type or any other type by the way).

**Comment by ptaillandier** [comment]
closed with my last commit
