### ISSUE TITLE
Ben Tre dataset: Java error: ConcurrentModificationException 

### ISSUE THREAD

**Issue by hqnghi88** [WARMTeam/CoVid19#14]
Just pull and launch today version and after around 200+ cycle , i get:
2 occurrences in 2 agents at cycle 251: Java error: ConcurrentModificationException
in ask bound.individuals where (flip(successful_contact_rate_human * reduction_factor) and (each.status = susceptible))  {
	do defineNewCase ;
}

ConcurrentModificationException: null
java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1388)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
one.util.streamex.AbstractStreamEx.rawCollect(AbstractStreamEx.java:68)
when applying the where operator on [Individual(2547),Individual(180),Individual(180),Individual(194),Individual(463),Individual(464),Individual(463),Individual(464),Individual(682),Individual(682),Individual(1173),Individual(1445),Individual(1173),Individual(1568),Individual(1445),Individual(1568),Individual(2435),Individual(2435),Individual(1553),Individual(1553)] and flip(successful_contact_rate_human * reduction_factor) and (each.status = susceptible)
in ask bound.individuals where (flip(successful_contact_rate_human * reduction_factor) and (each.status = susceptible))  {
	do defineNewCase ;
}

in agents Individual180, No Containment

**Comment by hqnghi88** [comment]
It works without Parallelisme of experiment, i close this as we dont tackle this now, i think

**Comment by AlexisDrogoul** [comment]
Hum... Parallelism of experiment ? or simulations ? It should work in the second case, no matter what !

**Comment by hqnghi88** [comment]
Sorry, of simulations, you are totally right, my bad

**Comment by AlexisDrogoul** [comment]
So it should normally work... 

Second thing not so clear (and more for @ptaillandier ): the bound.individuals expression returns a list where individuals appear two times.. Is it normal ?

**Comment by ptaillandier** [comment]
No, I do not understand why.... before entering into a new building (adding themselves to the individuals list), individuals are supposed to leave the previous one (remove themselves from the individuals list)

**Comment by hqnghi88** [comment]
i used old built (30 mars), i just rebuild a new one from git base, everything is ok.
Sorry for disturbing.

**Comment by hqnghi88** [comment]
> test comment from slack
<sub>[View in Slack](https://irdvietnam.slack.com/archives/C010KSVMRBR/p1585731986090700)</sub>
