### ISSUE TITLE
The primtive or action ... cannot be resolved when using the Covid 19 kit

### ISSUE THREAD

**Issue by NealT87** [WARMTeam/CoVid19#15]
I downloaded the latest version for windows + JDK(1.8), then downloaded your Covid 19 kit and imported it to the platform as instructed.
seem to not able to run the models because of the following primitive missing:
'folder_exists'
'gauss_rnd'
lognormal_rnd'
'weibull_rnd'

**the error  texts are:**
1. The primitive or action 'folder_exists' cannot be resolved (either it is not defined or not accessible). Resource: "/CoVid19 Modeling Kit/Experiments/Abstract Experiment.gaml"

2. The primitive or action 'gauss_rnd' cannot be resolved (either it is not defined or not accessible) Resource: /CoVid19 Modeling Kit/Model/Functions.gaml

3. The primitive or action 'lognormal_rnd' cannot be resolved (either it is not defined or not accessible) Resource: /CoVid19 Modeling Kit/Model/Functions.gaml

4. The primitive or action 'weibull_rnd' cannot be resolved (either it is not defined or not accessible) Resource: /CoVid19 Modeling Kit/Model/Functions.gaml

I think it might be version related as these function might be missing in older version, although i downloaded the latest one. 

Tried to update and install plugins but then it does not starts any more(other have referred to the update problem already)

**Comment by hqnghi88** [comment]
Dear, 
For this kit, it is recommended to use the newest version (continuous build) of GAMA. You can download here https://github.com/gama-platform/gama/releases/tag/continuous

**Comment by hqnghi88** [comment]
Dear,
For this kit, it is recommended to use the continuous build of gama (you can find it here https://github.com/gama-platform/gama/releases/tag/continuous ) .
